CREATE  INDEX UQ_INDEX_EMAIL ON AIRBNB_SCHEMA."User" (EMAIL);

CREATE  INDEX UQ_INDEX_PROPERTY_ID ON AIRBNB_SCHEMA."Property" (PROPERTY_ID);

CREATE  INDEX UQ_INDEX_BOOKING ON AIRBNB_SCHEMA."Booking" (BOOKING_ID);

CREATE  INDEX UQ_INDEX_BOOKING_PAYMENT ON AIRBNB_SCHEMA."Payment" (BOOKING_ID);
CREATE INDEX UQ_INDEX_PROPERTY_ID_BOOKING ON AIRBNB_SCHEMA."Booking" (PROPERTY_ID);
ANALYZE AIRBNB_SCHEMA."User";

EXPLAIN
ANALYZE
SELECT
	*
FROM
	AIRBNB_SCHEMA."User"
WHERE
	EMAIL = 'alice.johnson@example.com';