SELECT
	U.FIRST_NAME,
	U.LAST_NAME,
	U.EMAIL,
	B.BOOKING_ID,
	P.NAME,
	PA.AMOUNT
FROM
	AIRBNB_SCHEMA."User" U
	 JOIN AIRBNB_SCHEMA."Booking" B ON U.USER_ID = B.USER_ID
	 JOIN AIRBNB_SCHEMA."Property" P ON B.PROPERTY_ID = P.PROPERTY_ID
	LEFT JOIN AIRBNB_SCHEMA."Payment" AS PA ON PA.BOOKING_ID = B.BOOKING_ID;


EXPLAIN ANALYZE
 SELECT
	U.FIRST_NAME,
	U.LAST_NAME,
	U.EMAIL,
	B.BOOKING_ID,
	P.NAME,
	PA.AMOUNT
FROM
	AIRBNB_SCHEMA."User" U
	 JOIN AIRBNB_SCHEMA."Booking" B ON U.USER_ID = B.USER_ID
	 JOIN AIRBNB_SCHEMA."Property" P ON B.PROPERTY_ID = P.PROPERTY_ID
	LEFT JOIN AIRBNB_SCHEMA."Payment" AS PA ON PA.BOOKING_ID = B.BOOKING_ID;
